### ISSUE TITLE
Manage dashboard timewindow within a widget

### ISSUE THREAD

**Issue by tagliala** [thingsboard/thingsboard#1466]
Hi,

I would like to know if it is possible to manage the dashboard timewindow within a widget.

I need this because I need to disable some time settings, such as aggregation (must be none), real time, hour and minutes (must be 00:00) and show the history based just on a time period selected by the user

I'm able to show the values of the dashboard timewindow in a static widget, but I cannot find a way to update the settings back.

I see that the ng-submit action of the form is `vm.update()`, but that function does not exist in the context of the widget

This is the static widget I'm using

HTML
```html
<form name="theForm2" ng-submit="action()">
    <fieldset ng-disabled="$root.loading">
        <section layout="column">
            <tb-datetime-period ng-required="true" ng-model="vm.dashboardTimewindow.history.fixedTimewindow"
                style="padding-top: 8px;"></tb-datetime-period>
        </section>
        <md-input type="hidden" ng-model="vm.dashboardTimewindow.history.historyType"
            value="1"></md-input>
        <md-input type="hidden" ng-model="vm.dashboardTimewindow.aggregation.type"
            value="NONE"></md-input>
        <span flex></span>
        <section layout="row" layout-alignment="start center">
            <span flex></span>
            <md-button ng-disabled="$root.loading || theForm2.$invalid || !theForm2.$dirty"
                type="submit" class="md-raised md-primary">
                {{ 'action.update' | translate }}
            </md-button>
        </section>
    </fieldset>
</form>
```

JS
```js
self.onInit = function() {
    self.ctx.$scope.action = function() {
        // self.ctx.$scope.vm.update() does not exixt. what to do here?
    };
};
```

**Comment by vparomskiy** [comment]
You can use this function inside your widget to manage time window
https://thingsboard.io/docs/user-guide/contribution/widgets-development/#timewindow-functions

**Comment by jktu2870** [comment]
Hi @tagliala !
Try next:

html
```
<form name="theForm2" ng-submit="action()">
    <fieldset ng-disabled="$root.loading">
        <section layout="column">
            <tb-datetime-period ng-required="true" ng-model="timeModel"
                style="padding-top: 8px;"></tb-datetime-period>
        </section>
        <md-input type="hidden" ng-model="ctx.dashboardTimewindow.history.historyType"
            value="1"></md-input>
        <md-input type="hidden" ng-model="ctx.dashboardTimewindow.aggregation.type"
            value="NONE"></md-input>
        <span flex></span>
        <section layout="row" layout-alignment="start center">
            <span flex></span>
            <md-button ng-disabled="$root.loading || theForm2.$invalid || !theForm2.$dirty"
                type="submit" class="md-raised md-primary">
                {{ 'action.update' | translate }}
            </md-button>
        </section>
    </fieldset>
</form>
```

js
```
let $scope;
self.onInit = function() {
    $scope = self.ctx.$scope;
    $scope.ctx = self.ctx;
    $scope.timeModel = {
        startTimeMs: $scope.ctx.dashboardTimewindow.history.fixedTimewindow.startTimeMs,
        endTimeMs: $scope.ctx.dashboardTimewindow.history.fixedTimewindow.endTimeMs
    };
    self.ctx.$scope.action = function() {
        ctx.dashboard.dashboardTimewindowApi.onUpdateTimewindow($scope.timeModel.startTimeMs, $scope.timeModel.endTimeMs);
    };
    
    $scope.$on('dashboardTimewindowChanged', function () {
        $scope.timeModel = {
            startTimeMs: $scope.ctx.dashboardTimewindow.history.fixedTimewindow.startTimeMs,
            endTimeMs: $scope.ctx.dashboardTimewindow.history.fixedTimewindow.endTimeMs
        };
    })
};
```

**Comment by jktu2870** [comment]
@tagliala Have that example done the trick?

**Comment by tagliala** [comment]
@jktu2870 thanks for the suggestion. At the moment I'm not able to check this because I'm working on something else.

I'm going to close here, I will reopen if the trick will not work

**Comment by woodyjon** [comment]
Yes @jktu2870, your example works! Thanks, very helpful.

**Comment by hallard** [comment]
Dear @jktu2870 
This is working fine, thanks, any idea to do the same changing timewindow of the widget itself, not hte dashbaord? I've got timestamp of begin and end on device server attributes and just would like to set timewindow based on this. thanks

**Comment by nsahasra** [comment]
@jktu2870 : Is the code snippet mentioned is supposed to work as is? It throws an error "$scope.$on" is not a function?

**Comment by jktu2870** [comment]
@nsahasra What is your current version of TB? 
Example will not work with TB v3.0+

**Comment by devdoob** [comment]
For future readers.... this can be achieved in newer versions as well via this approach 

[Change dashboard timewindow from ActionsApi with clicked datapoint timestamp #2009
](https://github.com/thingsboard/thingsboard/issues/2009)

**Comment by SpieringsAE** [comment]
@devdoob Do you know where to find the documentation for what is happening in that code snippet?
I would like to conditionally set the time frame to the "Last" mode with some time from where to start but I am unable to find how to do that, I'm not even able to find anything like what is linked on the thingsboard website.

**Comment by leitinhakk** [comment]
> @devdoob Do you know where to find the documentation for what is happening in that code snippet? I would like to conditionally set the time frame to the "Last" mode with some time from where to start but I am unable to find how to do that, I'm not even able to find anything like what is linked on the thingsboard website.

I'm sorry, where should I put the code used in that issue? And can I use the same HTML?

**Comment by devdoob** [comment]
Yes put it wherever you want to trigger an action.... either in widget actions or custom widget..this will also work in markdown widgets

**Comment by t0mZ4** [comment]
@jktu2870 any idea how to make it work on TB3.0+ ? anyone?>

**Comment by apachler** [comment]
I am working with this widget to step through 8 hour shifts in TB 3.7.0. Maybe that helps?
[timewindowsetterv1.json](https://github.com/user-attachments/files/16885052/timewindowsetterv1.json)
