### ISSUE TITLE
How can I get the current logged user info

### ISSUE THREAD

**Issue by lmax25** [thingsboard/thingsboard#3013]
Hello !
Please tell me how can I get the current logged user info and display it's profile (name, email, etc) into a HTML widget.
I need the variable names.
Thank You !

Environment
OS: Win 7 x64
ThingsBoard: 2.5.2
Browser: Chrome

**Comment by RondoRonaldo** [comment]
You can use the next code to retrieve first and last names in custom widgets using ThingsBoard below version 3.0:

var $injector = self.ctx.$scope.$injector;
var $scope = self.ctx.$scope;
var userService = $injector.get('userService');
 $scope.firstName = userService.getCurrentUser().firstName;
 $scope.lastName = userService.getCurrentUser().lastName;

In HTML  block use the next code to represent this information:

<div>{{firstName}}</div>
<div>{{lastName}}</div>

**Comment by jskillen** [comment]
Based on errors I've seen shouldn't the userService be retrieved as follows:

var userService = $injector.get(self.ctx.servicesMap.get('userService'));

Kindly correct if I'm wrong.

**Comment by Manusisko** [comment]
> 
> 
> Based on errors I've seen shouldn't the userService be retrieved as follows:
> 
> var userService = $injector.get(self.ctx.servicesMap.get('userService'));
> 
> Kindly correct if I'm wrong.
> 
> **EDIT**
> 
> **Neither of these methods work in TB PE 3.1.1.**
> 
> @RondoRonaldo your code produces:
> 
> "Widget Error: NullInjectorError: R3InjectorError(e)[userService -> userService -> userService -> userService]:
> NullInjectorError: No provider for userService!"
> 
> My code produces:
> 
> "Widget Error: TypeError: userService.getCurrentUser is not a function"
> 
> IMO this should not be closed.

`self.ctx.currentUser`  is equivalent to userService.getCurrentUser() in V2.5
