### ISSUE TITLE
update from 3.6.4 to 3.7 error all widget in edit mode

### ISSUE THREAD

**Issue by Steve7394** [thingsboard/thingsboard#11226]
**Describe the bug**
after updating 3.6.4 to 3.7 in dashboard on edit mode all widget has error sth like
 
Widget Error:
self.ctx.$scope.entitiesTableWidget.onEditModeChanged is not a function

![Screenshot from 2024-07-17 17-34-25](https://github.com/user-attachments/assets/b41da119-e6b8-4f19-be2c-bd00732ae452)

**Comment by Backdraft007** [comment]
Did you clear the browser cache with CTRL+F5?

**Comment by epalchenko** [comment]
Hello,
Please describe your environment and provide install.log file. Also, provide the detailed steps you used to perform the upgrade and provide the output from the following command:
`dpkg -l thingsboard`

**Comment by Steve7394** [comment]
Ok the environment is
Build from source on ubuntu 22.0.4
I go forward as described in [https://thingsboard.io/docs/user-guide/install/upgrade-instructions/](url)
Then clean node _modules from ui dorectoru
And then run the upgrade-devel.sh 
And after that run src api with command
mvn clean install
And the ui in ui directory with commamd

Everything work properly without any error ...
And even the dashboard work smoothly
But when i click on edit mode of dashboard the error show up on every widget! And after that every thing work dummy untill refreshing the page.

**Comment by Steve7394** [comment]
@Backdraft007 yesh but nothing happened!

**Comment by mykhailokornieiev** [comment]
We're letting you know that this issue, labeled as "help wanted", has been open for a while. This label is used to seek support from the GitHub community, especially for issues that fall outside the scope of the ThingsBoard support team's expertise. Unfortunately, there hasn't been any community input or progress on this issue over the month(s). We're closing this ticket to keep our repository well-maintained and focused on active issues. We appreciate your patience and understanding.
