### ISSUE TITLE
Update Hiearchy Widget BUG v.3.9.0PE

### ISSUE THREAD

**Issue by AlexSP-I4** [thingsboard/thingsboard#12503]
After updating to 3.9.0 my bulk update widget i created gives an error on start, and it stops the hierarchy table widget from displaying any customers until i remove the widget and refresh. I attempted to remove all code from that widget and only have it showing front end code, and it still gives off an error. Any ideas?

The error
chunk-O2ERKNLN.js:7 ERROR TypeError: $(...).jstree is not a function

![Image](https://github.com/user-attachments/assets/8d8df0d4-f52b-4766-806f-e0576678c53a)

![Image](https://github.com/user-attachments/assets/b23518de-950c-463b-93dd-9e66423ba77e)

**Comment by devaskim** [comment]
Did you try to clear browser cache? Sometimes it helps in case of TB updates.

**Comment by SecureProcessIntelligence** [comment]
I can reproduce this issue.
If there is an entity Hierarchy widget on the same dashboard that also has a custom widget using this resource,
"https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"
 you will see the error on page refresh and the Hierarchy  be blank.

Cntrl+F5  / refresh Does not help,
then when you navigate to another dashboard with just the entity Hierarchy widget, you will see it blank / error , unless you refresh

**Comment by SecureProcessIntelligence** [comment]
I found a fix,
we specified the latest version of jQuery https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js and also added https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.12/jstree.min.js as this is now needed also.

Now the question remains, why does that error affect the entity Hierarchy widget
